language: go
go:
- '1.15'
services:
- docker
script:
- make test-docker
notifications:
  slack:
    secure: xWHoC0AUA0HBmnI2wRXvWcFIjYvAQkzbc025C0Uy77saUxjpOvLAaE7/jl7xojZtl1njf7vP1ZcbqF+P1yrTtB9nXwqEcHMdPSmqVbR5D0dKGp9c23KMwqbJfCaOgl5DWE1mUuSwd5IaKoDFEGMCLYaCsFjuIqaw4qoKctBgltnY723bRNsy2bbscs8IO7OnWIFRMqYTS8MmavZw07y8aP4xI5CgPR5ZbgXGLKEk01DRA240dS6+xRlVGDy6Vf58X35TDuJSFkimiY07xsfWI+ZIGqjL83+7xNrK7m5jqLIM57cARNvtVppMd5HUd249GjwkDCx3lsKohN4DhR1aI/rmoSUhyjoSM7Kj4CubLxSPwzpHhTWQHXLqofAdTpUqpfeVa5Alx1KqhHeVNE+7UaxVvuPQE1n9ickiH0znoHGFfjgwIz56rAYyt/qdm4SHTu6wmiDboCkf6GLvH++Kr/dZtjhWTi2PolgdLZbAR8OIEETfpp4j4pxQwwl/DE4h3IiKFES6Jd/TjrmUa7QLFOheFZyyzZ6MVP8Wa4YjeBp8+qRoBxWBNUSFp9w0QpO3eU/zvw+AOltDSW5Ph+VB1LuW+275MEGM9hw2cERbvOWoiE66o9rerSqEuknB2CC7/0mdOmIiTIoreArzSNJzwKvCeyCYLcvVmChuvxgQ/bg=
